# -*- coding: utf-8 -*-
"""MLP_MNIST_Emanoel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Ib1ORibXkSLQxOdWTO9pXcsR9YA6Dul
"""

# Imports principais
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

import numpy as np
import matplotlib.pyplot as plt

# Versão do TF (só para conferência no print)
print("TensorFlow:", tf.__version__)

# Carregar o conjunto de dados MNIST (imagens 28x28 de dígitos 0-9)
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Dimensões
print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_test:", X_test.shape, "y_test:", y_test.shape)

# Normalizar pixels para [0, 1]
X_train = X_train.astype("float32") / 255.0
X_test  = X_test.astype("float32") / 255.0

# Flatten: 28x28 -> 784
X_train = X_train.reshape(-1, 28 * 28)
X_test  = X_test.reshape(-1, 28 * 28)

# One-hot encoding dos rótulos
num_classes = 10
y_train_cat = to_categorical(y_train, num_classes)
y_test_cat  = to_categorical(y_test, num_classes)

print("Após preprocessamento:")
print("X_train:", X_train.shape, "y_train_cat:", y_train_cat.shape)
print("X_test:", X_test.shape, "y_test_cat:", y_test_cat.shape)

model = models.Sequential([
    layers.Input(shape=(28 * 28,)),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.2),
    layers.Dense(num_classes, activation="softmax")
])

model.summary()

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

# Treino
history = model.fit(
    X_train, y_train_cat,
    validation_split=0.1,     # 10% do treino para validação
    epochs=10,                # aumentar para 15-20 (melhor acurácia)
    batch_size=128,
    verbose=1
)

# Visualizar curva de aprendizado
plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.plot(history.history["loss"], label="train")
plt.plot(history.history["val_loss"], label="val")
plt.title("Loss")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history["accuracy"], label="train")
plt.plot(history.history["val_accuracy"], label="val")
plt.title("Accuracy")
plt.legend()
plt.show()

test_loss, test_acc = model.evaluate(X_test, y_test_cat, verbose=0)
print(f"Acurácia em teste: {test_acc:.4f}")

# Selecionar alguns exemplos aleatórios
indices = np.random.choice(len(X_test), size=12, replace=False)
samples = X_test[indices]
labels_true = y_test[indices]

# Previsões
probs = model.predict(samples, verbose=0)
labels_pred = probs.argmax(axis=1)

# Plotar
plt.figure(figsize=(10,8))
for i, idx in enumerate(indices):
    plt.subplot(3, 4, i+1)
    plt.imshow(samples[i].reshape(28,28), cmap="gray")
    plt.title(f"Real: {labels_true[i]} | Pred: {labels_pred[i]}")
    plt.axis("off")
plt.tight_layout()
plt.show()
